# Generated by Django 5.2.2 on 2025-06-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Dieases', '0001_initial'),
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ProfilePic', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('admitDate', models.DateField()),
                ('diease', models.ManyToManyField(to='Dieases.dieases')),
                ('doctor', models.ManyToManyField(to='Doctors.doctor')),
            ],
        ),
    ]
