# Generated by Django 5.2.2 on 2025-10-24 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dieases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieases',
            name='treatmentAvgDuration',
            field=models.CharField(max_length=50),
        ),
    ]
